### ISSUE TITLE
Can't execute versions 0.1.14 and 0.1.13

### ISSUE THREAD

**Issue by victorperin** [h2non/node-imaginary#15]
This version is not working. The latest working version is `0.1.12`.

**NodeJS Versions**: 9.2.0 and 8.9.2

**How to reproduce**: `npm i -g imaginary@0.1.14 && imaginary`

**Error output**:
```
module.js:544
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/victor/.nvm/versions/node/v9.2.0/lib/node_modules/imaginary/bin/imaginary:6:19)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

If you need any other information, I can provide, just ask :)

**Comment by h2non** [comment]
Please, upgrade it to `v0.1.16`.
